//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 第二组综合设计地铁购票系统.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string Username { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public string IDCard { get; set; }
        public string Phonenum { get; set; }
        public Nullable<int> jifen { get; set; }
        public Nullable<int> money { get; set; }
    }
}
